// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0Br_u5c4YbXn_TlSZHw3aWFCKv9drdY',
    appId: '1:990746892901:web:003e699718464ae28d448c',
    messagingSenderId: '990746892901',
    projectId: 'notes-ee036',
    authDomain: 'notes-ee036.firebaseapp.com',
    storageBucket: 'notes-ee036.appspot.com',
    measurementId: 'G-PL2SMB3LLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLYiKeDKm87G5NVZ-bFUZzOy-Ygz2V3kA',
    appId: '1:990746892901:android:f084921a7db14b788d448c',
    messagingSenderId: '990746892901',
    projectId: 'notes-ee036',
    storageBucket: 'notes-ee036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqjRBChFqURNUODKbRgLVLooK082i998',
    appId: '1:990746892901:ios:c88196fb15f4ba398d448c',
    messagingSenderId: '990746892901',
    projectId: 'notes-ee036',
    storageBucket: 'notes-ee036.appspot.com',
    iosBundleId: 'com.example.notes',
  );
}
